### ISSUE TITLE
BUG: function getinfo returns itag 22 without contentLength, which makes function chooseformat get unexpected result when quality is highest or lowest

### ISSUE THREAD

**Issue by iii8iii** [fent/node-ytdl-core#879] opened 2021-02-13 11:29 UTC
GREAT JOB

- Are you on the latest version of ytdl-core?
YES, I AM ON THE  LATEST VERSION

- BUG: function getinfo returns itag 22 without contentLength, which makes function chooseformat get unexpected result when quality is highest or lowest

please recheck if `itag 22` is without contentLength
```const ytdl = require('ytdl-core')
 const url = 'https://www.youtube.com/watch?v=aqz-KE-bpKQ';
 const stream = ytdl(url)
 const info = await ytdl.getInfo(url)
 const  infoWithoutContentlength = info.filter(format=>!format.contentLength)
 console.log(infoWithoutContentlength)
```
it seems not only this video any video itag 22 without contentLength

if yes. function `sortFormats` in `format-utils.js` 
```
/**
 * Sort formats from highest quality to lowest.
 *
 * @param {Object} a
 * @param {Object} b
 * @returns {number}
 */
exports.sortFormats = (a, b) => sortFormatsBy(a, b, [
  // Formats with both video and audio are ranked highest.
  format => +!!format.isHLS,
  format => +!!format.isDashMPD,
  format => +(format.contentLength > 0),
  format => +(format.hasVideo && format.hasAudio),
  format => +format.hasVideo,
  format => parseInt(format.qualityLabel) || 0,
  getVideoBitrate,
  getAudioBitrate,
  getVideoEncodingRank,
  getAudioEncodingRank,
]);
```
will make itag 22 to be the last format 

function `chooseFormat`  in `format-utils.js` 
```
/**
 * Choose a format depending on the given options.
 *
 * @param {Array.<Object>} formats
 * @param {Object} options
 * @returns {Object}
 * @throws {Error} when no format matches the filter/format rules
 */
exports.chooseFormat = (formats, options) => {
  if (typeof options.format === 'object') {
    if (!options.format.url) {
      throw Error('Invalid format given, did you use `ytdl.getInfo()`?');
    }
    return options.format;
  }

  if (options.filter) {
    formats = exports.filterFormats(formats, options.filter);
  }

  let format;
  const quality = options.quality || 'highest';
  switch (quality) {
    case 'highest':
      format = formats[0];
      break;

    case 'lowest':
      format = formats[formats.length - 1];
      break;
......
```
will return itag 18(360p,hasVideo,hasAudio) when quality is highest
will return itag 22(720p,hasVideo,hasAudio) when quality is lowest

720p is better than 360p,  right?

**Comment by redbrain** [comment] 2021-02-13 13:58
Duplicate of #770, please close.

**Closed** 2021-02-13 14:09 UTC
