### ISSUE TITLE
Error: Status Code 416

### ISSUE THREAD

**Issue by S0LDR** [fent/node-ytdl-core#669] opened 2020-07-23 02:26 UTC
```Error: input stream: Status code: 416
    at ClientRequest.<anonymous> (C:\Users\Soldr\WebstormProjects\ezbot\node_modules\.pnpm\miniget@2.0.1\node_modules\miniget\dist\index.js:156:27)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at HTTPParser.execute (<anonymous>)
    at TLSSocket.socketOnData (_http_client.js:469:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
```
once this happens, all music stops playing. I am implementing this with Discord.JS and opusscript.

**Comment by MrZBou** [comment] 2020-07-23 05:55
Duplicate of #659

**Closed** 2020-07-29 17:27 UTC
Labels: duplicate
