### ISSUE TITLE
Error: input stream: Could not find player config

### ISSUE THREAD

**Issue by amitojsingh366** [fent/node-ytdl-core#745] opened 2020-10-25 08:40 UTC
I keep encountering the error `Error: input stream: Could not find player config` and it occurs randomly at random intervals on random videos. Its very annoying cuz when it starts it will continue to happen.

**Comment by Asaduji** [comment] 2020-10-25 08:51
dupe of #738, update to latest and try again

**Comment by amitojsingh366** [comment] 2020-10-25 13:16
Using latest ytdl-core still same issue....

**Comment by TimeForANinja** [comment] 2020-10-25 21:23
let us keep discussion in #738

**Comment by amitojsingh366** [comment] 2020-10-25 21:32
A bit more info about the system:
#29~18.04.1-Ubuntu SMP Tue Oct 6 17:14:23 UTC 2020 (x86_64).
I also get the error when I test run the code on my MacBook Air with macOS 10.15.7 (19H2). But it is less frequent on the Mac

**Comment by fent** [comment] 2020-10-25 22:26
are you using ytdl-core-discord?

**Comment by amitojsingh366** [comment] 2020-10-25 22:27
No i'm using just `ytdl-core` on version 3.4.2

**Comment by amitojsingh366** [comment] 2020-10-26 06:08
Ok so `ytdl-core v4.0.0` fixes the errors. Thanks a lot!

**Comment by fent** [comment] 2020-10-26 06:34
it was fixed in v3.4.2

**Comment by amitojsingh366** [comment] 2020-10-26 07:34
Yes im aware of that but maybe as I've been using your library from a long time the previous versions were cached somehow by npm and v4.0 somehow fixed it.
Thanks anyways and keep up the good work!

**Comment by amitojsingh366** [comment] 2020-10-26 07:36
Update: the previous error docent come at all but now its rare but I get the error `Error: input stream: Error parsing info: Unable to retrieve video metadata` occurred only 2x till now

**Comment by fent** [comment] 2020-10-26 11:16
yep, i've seen it a few times. ytdl-core retries the request if this happens, usually that fixes it.

i'll have to have it retry it a few more times with backoff

**Comment by amitojsingh366** [comment] 2020-10-26 11:43
Oh ok. 
I guess this issue is solved

**Closed** 2020-10-26 11:44 UTC
Labels: old version
