### ISSUE TITLE
irl-test.js failing for Vevo even though youtube-dl works fine

### ISSUE THREAD

**Issue by russtee** [fent/node-ytdl-core#259] opened 2018-01-09 00:28 UTC
The following videos fail for the irl-test.js even though youtube-dl is able to download them fine:
```
  'Regular video'           : 'mgOS64BF2eU',
  'VEVO'                    : 'qQ31INpjXX0',
  'VEVO 2'                  : 'pJk0p-98Xzc',
```

The error given is:
```
This video is unavailable
```

I'm seeing similar behaviour with quite a few other videos e.g.
[https://www.youtube.com/watch?v=4TPqUvy1vYU](https://www.youtube.com/watch?v=4TPqUvy1vYU)

<img width="593" alt="screen shot 2018-01-09 at 00 27 27" src="https://user-images.githubusercontent.com/3050226/34699199-e681843e-f4d3-11e7-88db-25e31a1fe6b9.png">

**Comment by fent** [comment] 2018-01-09 02:04
Dupe of #258

**Closed by fent** 2018-01-09 02:04 UTC
Labels: bug, duplicate
