### ISSUE TITLE
getInfo does not return all linked media for fetched video

### ISSUE THREAD

**Issue by AKASGaming** [fent/node-ytdl-core#931] opened 2021-06-02 19:01 UTC
When using ytdl.getInfo() on [This Video](https://www.youtube.com/watch?v=TtAfhr_3NKY), it only returns the last songs, _seen below_

![image](https://user-images.githubusercontent.com/25405047/120537444-ee9c2800-c3aa-11eb-8c39-52ed717a2584.png)

```
  media: {
    'suggested by umg': 'Migos - Straightenin (Official Video)',
    'suggested by umg_url': 'https://www.youtube.com/watch?v=E553AnMAvlU',
    song: 'Bamboleo',
    song_url: 'https://www.youtube.com/watch?v=BXbrXRIr2F4',
    category: 'Music',
    category_url: 'https://music.youtube.com/',
    artist: 'Gipsy Kings',
    artist_url: 'https://www.youtube.com/channel/UCMSvtHZgu0-n6ISejwL8rAw',
    'licensed to youtube by': 'WMG, SME (on behalf of Nonesuch); LatinAutor, LatinAutor - Warner Chappell, UNIAO BRASILEIRA DE EDITORAS DE MUSICA - UBEM, PEDL, União Brasileira de Compositores, LatinAutor - SonyATV, Sony ATV Publishing, UMPI, Warner Chappell, LatinAutorPerf, ASCAP, and 14 Music Rights Societies',
    album: 'Gipsy Kings',
    writers: 'Nicolas Reyes, Jahloul Bouchikhi, Simón Díaz, Tonino Baliardo'
  }
```

I think it'd be nice to include every song in the video

**Comment by TimeForANinja** [comment] 2021-06-02 19:18
duplicate of https://github.com/fent/node-ytdl-core/issues/920

**Closed by TimeForANinja** 2021-06-02 19:18 UTC
