### ISSUE TITLE
Problem with cathing MinigetError 410

### ISSUE THREAD

**Issue by GustavPS** [fent/node-ytdl-core#1002] opened 2021-09-07 17:29 UTC
I'm having problems catching MinigetError: Status code: 410

    MinigetError: Status code: 410
        at ClientRequest.<anonymous> (/node_modules/miniget/dist/index.js:210:27)
        at Object.onceWrapper (node:events:514:26)
        at ClientRequest.emit (node:events:394:28)
        at HTTPParser.parserOnIncomingClient (node:_http_client:621:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
        at TLSSocket.socketOnData (node:_http_client:487:22)
        at TLSSocket.emit (node:events:394:28)
        at addChunk (node:internal/streams/readable:315:12)
        at readableAddChunk (node:internal/streams/readable:289:9)
        at TLSSocket.Readable.push (node:internal/streams/readable:228:10) {
      statusCode: 410

I am probably missing something obvious, but I've been browsing through the examples and other issues mentioning MinigetErrors and I can't find anything. I'm trying to catch the error with the "error" event:

    const startDownload = () => {
        let starttime = null;
        const download = ytdl("https://www.youtube.com/watch?v=" + trailer, {quality: 'highestvideo', filter: format => format.container === 'mp4'});
        download.pipe(fs.createWriteStream(path));
        download.once("response", () => {
            starttime = Date.now();
        });
        download.on('error', err => {
            logger.ERR(`Error downloading trailer: ${err}`);
            download.destroy();
            resolve(false);
            return;
        });

The "error" event is not firing, instead the MinigetError is thrown. I'm not always getting the 410 but I'm suspecting it is because the video might be age restricted, or maybe private. But all I want to do is to catch the error so my entire program doesn't crash.

**Comment by gatecrasher777** [comment] 2021-09-08 22:08
The 410, 403, 404 miniget errors happen at the getInfo stage, before the download stream is activated. If you break up your ytdl() request into ytdl.getInfo() and ytdl.downloadFromInfo() stages you should be able to catch those errors.

**Comment by TentacleSama4254** [comment] 2021-09-09 19:09
I've been getting this for a while, it's random and sometimes it works sometimes it doesn't. No idea what the cause is

**Comment by TimeForANinja** [comment] 2021-10-17 03:15
🤔 gonna mark this as a bug
a `ytdl.getInfo` - error should still get passed to the stream to be handled

**Comment by codeerror90** [comment] 2022-02-05 18:04
in my case I am using it in a whatsapp bot.

The solution was to change the command avoiding the word play.

Something very silly but that solved it.

**Comment by TimeForANinja** [comment] 2022-03-05 04:57
ok, closing this for now
* there is #1009 to keep a track of the 410-issue
* i am unable to recreate the `The "error" event is not firing`-Problem, which was the reason i left this open...

feel free to open a new issue if you'Re experiencing this problem again

**Closed by TimeForANinja** 2022-03-05 04:57 UTC
Labels: bug
