### ISSUE TITLE
[ Bug ] Confirm Age Error

### ISSUE THREAD

**Issue by SidisLiveYT** [fent/node-ytdl-core#926] opened 2021-05-24 12:57 UTC
**Issue**
> I faced this issue where it asks for Confirm Age and the Dev on the pacakge told me its node-ytdl-core bug  , Btw it never happened ! and My Bot got crashed unexpectedly ! with unhandled error .

**Screenshot**
<a href="https://imgur.com/gyrZ23v"><img src="https://i.imgur.com/gyrZ23v.png" title="source: imgur.com" /></a>

**Comment by vaaski** [comment] 2021-05-24 18:50
Seems like a duplicate of #923

I've opened a PR (#924) that temporarily fixes this issue, at the cost of slower info resolution.
You can use [resync-tv/node-ytdl-core](https://github.com/resync-tv/node-ytdl-core) for the meantime until #923 is fixed completely.

**Comment by gatecrasher777** [comment] 2021-06-22 07:42
I have seen this in some info requests:

```
 "playabilityStatus": {
    "status": "AGE_CHECK_REQUIRED",
    "reason": "This video may be inappropriate for some users.",
    ...
}
```

I don't think this playability case is anticipated in the current code.

**Comment by TimeForANinja** [comment] 2021-06-22 15:37
> AGE_CHECK_REQUIRED

Age restricted Videos should be accounted for

Also closing this issue as stale

**Closed by TimeForANinja** 2021-06-22 15:37 UTC
