### ISSUE TITLE
Status 429 error with new version (v4.4.5)

### ISSUE THREAD

**Issue by chrisr11** [fent/node-ytdl-core#871] opened 2021-02-04 02:35 UTC
Hi,

I am not sure what changed with v4.4.5 but almost all the videos are throwing error 429. I downgrade to v4.4.3 and the issue was resolved. Can someone please look into this?

**Comment by HexDevv** [comment] 2021-02-10 02:26
[Error 429 - Too Many Requests](https://httpstatuses.com/429)
_The user has sent too many requests in a given amount of time ("rate limiting")._

Your IP is blocked from Youtube. its a bit of an self explainable issue.

Get a new IP or wait for IPv6 block rotating to come out here: #713

**Comment by fent** [comment] 2021-02-10 02:33
there were no changes between v4.4.3 and v4.4.5 that would change the way ytdl is making requests

dupe of https://github.com/fent/node-ytdl-core/issues/635

**Closed by fent** 2021-02-10 02:33 UTC

**Comment by sdan41517** [comment] 2021-02-11 03:12
> [Error 429 - Too Many Requests](https://httpstatuses.com/429)
> _The user has sent too many requests in a given amount of time ("rate limiting")._
> 
> Your IP is blocked from Youtube. its a bit of an self explainable issue.
> 
> Get a new IP or wait for IPv6 block rotating to come out here: #713

I'm using a rotating proxy. I have tried with youtube-dl and it works but this node-ytdl has issues. So no, it's not an IP problem, something's changed...

**Comment by sdan41517** [comment] 2021-03-02 15:15
Still no updates?! When I downgrade to v4.4.3, it is working perfectly fine! This 429 issue started happening since v4.4.5

**Comment by HexDevv** [comment] 2021-03-03 12:58
bro did you not read what fent put?

> dupe of #635

**Comment by sdan41517** [comment] 2021-03-16 15:15
Have you not read what I stated? The issue is present in versions beyond 4.4.3.

> bro did you not read what fent put?
> 
> > dupe of #635
