### ISSUE TITLE
Error Status Code 429

### ISSUE THREAD

**Issue by uhFinn** [fent/node-ytdl-core#648] opened 2020-06-04 15:14 UTC
Im getting an error message: 

04.06 17:01:01 [Bot] (node:60) UnhandledPromiseRejectionWarning: Error: Status code: 429
04.06 17:01:01 [Bot] at ClientRequest.<anonymous> (/node_modules/ytdl-core/node_modules/miniget/dist/index.js:141:31)
04.06 17:01:01 [Bot] at Object.onceWrapper (events.js:417:26)
04.06 17:01:01 [Bot] at ClientRequest.emit (events.js:310:20)
04.06 17:01:01 [Bot] at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
04.06 17:01:01 [Bot] at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
04.06 17:01:01 [Bot] at TLSSocket.socketOnData (_http_client.js:469:22)
04.06 17:01:01 [Bot] at TLSSocket.emit (events.js:310:20)
04.06 17:01:01 [Bot] at addChunk (_stream_readable.js:286:12)
04.06 17:01:01 [Bot] at readableAddChunk (_stream_readable.js:268:9)
04.06 17:01:01 [Bot] at TLSSocket.Readable.push (_stream_readable.js:209:10)
04.06 17:01:01 [Bot] at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
04.06 17:01:01 [Bot] (node:60) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

After doing some research ive figured it may mean im sending too many requests however I dont believe this is the case as no-ones even used the music feature today & yesterday
Anyone else had this issue and know of a way to fix it

Edit: This was perfectly working a few days ago how it has randomly just *stopped*

**Comment by beaudry12087** [comment] 2020-06-05 14:34
I have encountered the same ''' Error: Status code: 429''' issue

**Comment by fent** [comment] 2020-06-07 03:10
dupe of https://github.com/fent/node-ytdl-core/issues/635

**Closed by fent** 2020-06-07 03:10 UTC
Labels: duplicate
