### ISSUE TITLE
Error on stream close before end

### ISSUE THREAD

**Issue by khionu** [fent/node-ytdl-core#65] opened 2016-01-21 12:45 UTC
This error is being thrown when I close the stream prior to the video being completed, every time. The stream is being piped into FFMpeg, then into Opus which then gets transmitted through a web socket on a voice chat. The end stream function is from the library which is handling FFMpeg and Opus. It's not having an issue with any other media types, though other youtube downloaders haven't been tried. This happens on NodeJS 4.2.x and 5.5.0.

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:860:11)
    at Pipe.onread (net.js:544:26)
```

**Comment by meew0** [comment] 2016-01-26 20:43
I've also had the issue with the same setup, and I wanted to share my workaround: https://github.com/meew0/Lethe/blob/master/lethe.js#L564

It's really hacky but it works.

**Comment by fent** [comment] 2016-01-30 17:21
How are you closing the stream?

**Comment by khionu** [comment] 2016-01-30 20:30
https://github.com/hydrabolt/discord.js/tree/master/src/Voice

This is the library that is being used, the link is directly to the components that deal with the audio.

**Comment by meew0** [comment] 2016-01-30 21:19
Specifically, this method is being used: https://github.com/hydrabolt/discord.js/blob/master/src/Voice/VoiceConnection.js#L63

**Comment by fent** [comment] 2016-01-30 23:39
Tried replicating by ending the stream early with `.end()`, but not getting an error :/

**Comment by khionu** [comment] 2016-01-31 09:18
May I prebundle something simple for you to test with? It would be a single JS file with Discord.JS and ytdl-core as dependencies, containing a basic test function.

**Comment by khionu** [comment] 2016-01-31 09:20
We've been quite baffled by it, not only by its occurrence, but how different program seems to have different rates of it occurring. For meew0's project `Lethe`, it's uncommon, but for me, it happens every time.

**Comment by fent** [comment] 2016-01-31 16:46
It would help but, reducing the problem to its simplest form would be easier to debug.

I made the following file to test but it's not giving an error.

```js
var ytdl = require('..');
var stream = ytdl('https://www.youtube.com/watch?v=6ySOK70gFPk');


var size;
stream.on('response', function(res) {
  size = res.headers['content-length'];
  console.log('size', size);
});

var dataEmitted = 0;
stream.on('data', function(chunk) {
  dataEmitted += chunk.length;
  console.log('on data', chunk.length, dataEmitted);
  if (dataEmitted / size >= 0.5) {
    console.log('ending');
    stream.end();
  }
});

stream.on('end', function() {
  console.log('emitted', dataEmitted);
});
```

**Comment by khionu** [comment] 2016-01-31 22:19
A friend of mine had a really long queue running in Lethe, took over 24 hours of playing to produce it. Given the error occurs 100% of the time with my setup, it'd be the less time consuming :/

I'll get you a ZIP. I host the code for my bot on a Registration-Required GitLab, but I can download it and delete what you don't need from the ZIP.

Umm..... the bot is Discord specific, and idk if you have an account or are familiar with it, but you can use it without making an account, but you would have to register an account for the bot, minimum.
http://discordapp.com/

(Zip in a few min)

**Comment by khionu** [comment] 2016-01-31 22:26
Apparently I pushed a partial fix to something :/ I was hoping to do this before going to bed, but I have to go to bed for now. First thing when I wake up.

**Comment by fent** [comment] 2016-02-13 05:27
Any update?

**Comment by demonicpagan** [comment] 2016-02-29 17:57
I am wondering the same about an update.

**Comment by Taconut** [comment] 2016-03-01 00:32
i'm getting an ECONNRESET error as well. Such a shame these bugs are so hard to reproduce.

**Comment by Kerryliu** [comment] 2016-03-10 16:30
yep, I've been getting the same issue.

**Closed** 2016-03-11 04:52 UTC

**Comment by fent** [comment] 2016-03-11 11:19
Just pushed a potential fix. I couldn't reproduce this so I'm not 100% certain.

Anyway, use `stream#destroy()`. Feel free to reopen this if it keeps happening with the new version.

**Comment by GexoXYZ** [comment] 2016-06-05 15:51
This still happens for nearly everyone using `discord.js`.

**Comment by fent** [comment] 2016-06-05 16:08
For which module? I don't see this as a dependency on discord.js

**Comment by GexoXYZ** [comment] 2016-06-05 16:49
It's just used for playing youtube audio, not necessarily a discord.js thing but everyone just uses it. See https://github.com/GexoXYZ/GeBot/blob/master/src/commands/voice/play.js#L57-L69

Basically error happens when the stream gets closed early, (when calling these functions) -> https://github.com/hydrabolt/discord.js/blob/master/src/Voice/VoiceConnection.js#L54-L95

**Comment by fent** [comment] 2016-06-06 00:12
Others here have already linked to discord.js, and to that specific steram closing functions. And haven't heard from them since the possible fix a while back. So I'm trying to see if they're using the latest version of this library, but I don't see where the version is specified. It's not in `package.json`

**Comment by GexoXYZ** [comment] 2016-06-06 00:25
This reportedly happens on versions after the potential fix (http://bit.ly/1X60BPT, http://bit.ly/1XvkUXB). A small portion of us is active in a chat for discord.js and this error is one of the most asked questions everyday. We just refer to meew0's workaround but that can't be the way to go. I've tried to debug this error for hours but I just didn't have any success (well I'm not really a good dev anyways but that aside).  Just letting you know that this bug is still persistent, would be really glad if this *somehow* could get fixed ^.^ I can provide you with a small script to reproduce this if you want but as others said this is not really consistent, so it's really frustrating :/

**Comment by fent** [comment] 2016-06-06 21:36
I wish I could debug this in a better way. If you can provide a script where you can reproduce this, please do so.

**Comment by khionu** [comment] 2016-06-06 22:27
I've stopped using Node for my Discord Bots, but I think this commit was for this issue, fwiw
https://github.com/qeled/discordie/commit/a7de2f4956b32744cf1d70c8652d65195ee219f7

**Comment by MergHQ** [comment] 2016-06-15 07:41
I'm getting a similar error, but it happen randomly while the stream is open. I'm not calling .end(), it just throws this error in the middle of the stream. Anyone know anything?

**Comment by GexoXYZ** [comment] 2016-06-15 09:05
Apparently it was an error on discord.js' end. Potential fixed in thr indev
branch.

**Comment by MergHQ** [comment] 2016-07-06 18:42
@GexoXYZ Still not fixed.

**Comment by jnwarner** [comment] 2017-04-23 16:14
Anything on this yet? I have the same issue as @MergHQ

**Comment by fent** [comment] 2017-04-23 18:01
Can you provide an example file where this can be replicated?

**Comment by jnwarner** [comment] 2017-04-23 18:15
I could try to make one, although I've been finding this issue in my bot script often. It appears more prone to destroying the stream when connection speeds are low.

**Comment by Cynigo** [comment] 2017-04-23 18:33
There's still a rather large chance that it's not this libs fault. I remember months ago when almost everyone using discord.js had this problem and thought it's this library's fault, and when a discord.js patch came out, it suddenly disappeared.

**Comment by jnwarner** [comment] 2017-04-23 18:41
I'm not sure which side the error belongs to, but both are telling me it is probably not them. I'm relatively new to node debugging and cannot seem to find where the error is coming from. If this helps at all, the StreamDispatcher object is not throwing any errors when a skip occurs, it just calls it's end function. A moderator on the discord.js support server sent this not too long ago: https://gyazo.com/c4ecd202d34c74dc627c941bae044cfd
