### ISSUE TITLE
Unexpected token ) in JSON at position 0

### ISSUE THREAD

**Issue by MikeDev96** [fent/node-ytdl-core#729] opened 2020-10-15 23:58 UTC
Randomly getting this issue on the latest version (3.4.0).

2020-10-16T01:03:22: Error: Error parsing info: Unexpected token ) in JSON at position 0
2020-10-16T01:03:22:     at exports.getBasicInfo (/home/migul/Documents/lucille-bot/node_modules/ytdl-core/lib/info.js:74:11)
2020-10-16T01:03:22:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-10-16T01:03:22:     at async Map.getOrSet (/home/migul/Documents/lucille-bot/node_modules/ytdl-core/lib/cache.js:24:19)
2020-10-16T01:03:22:     at async exports.getInfo (/home/migul/Documents/lucille-bot/node_modules/ytdl-core/lib/info.js:215:14)
2020-10-16T01:03:22:     at async Map.getOrSet (/home/migul/Documents/lucille-bot/node_modules/ytdl-core/lib/cache.js:24:19)

It's similar to another issue where if you call again it works fine, think was related to age restricted content.

I can't even put a plaster on it by catching the error and trying again because the error never makes it out of ytdl.

**I've tried wrapping the ytdl() call in a try/catch & I've tried adding an error event to the stream, neither of which fire.**

Please fix the error bubbling issue as well.

**Comment by Asaduji** [comment] 2020-10-16 00:21
dupe of #727

**Closed** 2020-10-16 02:17 UTC
Labels: duplicate
