### ISSUE TITLE
Playing livestream stopped working

### ISSUE THREAD

**Issue by silvinator** [fent/node-ytdl-core#409] opened 2019-02-01 14:08 UTC
My discord bot has been playing livestreams so far. But now he does not do this anymore, what am I doing wrong? I already tried the Itags 91,92,93,94 and 95, but it did not work. And sorry for my bad english, it's not my nativ language

```javascript
	const dispatcher = serverQueue.connection.playStream(ytdl(song.url, {quality: '93'}))
		.on('end', reason => {
			if (reason === 'Stream is not generating quickly enough.') console.log('Song ended.');
			else console.log(reason);
			serverQueue.songs.shift();
			play(guild, serverQueue.songs[0]);
		})
		.on('error', error => console.error(error));
	dispatcher.setVolumeLogarithmic(serverQueue.volume / 5);

	serverQueue.textChannel.send(`Ich spiele **${song.title}** (${song.url}) nur weil ich es will. Das du es auch willst ist nur ein zufall!`);
}
});

**Comment by FireController1847** [comment] 2019-02-02 01:42
Closing due to duplicate of #407, #399

**Closed by FireController1847** 2019-02-02 01:42 UTC
Labels: duplicate
