### ISSUE TITLE
Error: Status code: 429

### ISSUE THREAD

**Issue by Abhay07** [fent/node-ytdl-core#709] opened 2020-09-19 13:14 UTC
Error: Status code: 429

on running ytdl.getInfo(videoUrl)

```
StackTrace - Error: Status code: 429
    at ClientRequest.<anonymous> (/home/ubuntu/youtubecutter-backend/node_modules/miniget/dist/index.js:150:31)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:469:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10)

```

Can someone help ?

**Comment by Abhay07** [comment] 2020-09-19 13:24
Version - ytdl-core@3.2.2

**Comment by Roki100** [comment] 2020-09-19 19:14
dupe of #635

**Closed** 2020-09-25 03:59 UTC
Labels: duplicate
