### ISSUE TITLE
Browserify / parcel ytdl

### ISSUE THREAD

**Issue by ak1987** [fent/node-ytdl-core#604] opened 2020-04-11 16:32 UTC
Hello, i am trying to use your library (2.0.1) as a standalone-js file to be used in browsers.
I was trying to use parcel and browserify and got the following error:

bundle.js:15110 Uncaught (in promise) Error: Error parsing config: Unexpected token ; in JSON at position 71078
    at gotConfig (bundle.js:15110)
    at exports.getBasicInfo (bundle.js:15064)
    at async Object.exports.<computed> [as getBasicInfo] (bundle.js:15299)
    at async exports.getFullInfo (bundle.js:15172)
    at async Function.exports.<computed> [as getInfo] (bundle.js:15299)
    at /async http:/ytdl.loc/bundle.js:11367
gotConfig @ bundle.js:15110
exports.getBasicInfo @ bundle.js:15064
async function (async)
(anonymous) @ bundle.js:11367
60.ytdl-core @ bundle.js:11369
o @ bundle.js:1
r @ bundle.js:1
(anonymous) @ bundle.js:1

https://pastebin.com/PGwkpGEM contains console.log of config. It seems for some unknown reason config structure was corrupted.

The file i was trying to convert contains code:

var ytdl = require('ytdl-core');

(async () => {
  let result = await ytdl.getInfo("YySiE8DsQ0M");
  console.log(result);
})();

I have also
[bundle.txt](https://github.com/fent/node-ytdl-core/files/4464945/bundle.txt)
 attached bundle.js as txt file.

**Comment by fent** [comment] 2020-04-11 17:04
dupe of https://github.com/fent/node-ytdl-core/issues/585
this PR fixes it https://github.com/fent/node-ytdl-core/pull/599

**Closed by fent** 2020-04-11 17:04 UTC
Labels: duplicate
