### ISSUE TITLE
Error while validating

### ISSUE THREAD

**Issue by hypo-thesis** [fent/node-ytdl-core#740] opened 2020-10-23 19:19 UTC
I have got the following code to validate the url : 

```
app.get('/getinfo', async (req, res) => {
  const valid = ytdl.validateURL(req.query.data)
  if (valid) {
    info = await getInfo(req.query.data)
    if(info !== null){
    +info.duration < 3500000 ? res.status(200).json({ info: info }) : res.status(400).json({ info: 'CANNOT CONVERT VIDEOS LONGER THAN 60 MINS' })
  }else{
    res.status(500).json({ info: 'SERVER RETURNED ERROR, TRY AGAIN !' })
  }
  } else {
    res.status(400).json({ info: 'invalid url' })
  }
});
```

However I get 

```
/www/wwwroot/localhost/api/node_modules/ytdl-core/lib/info.js:74
    throw Error(`Error parsing info: ${err.message}`);
          ^

Error: Error parsing info: Unexpected token ) in JSON at position 0
    at exports.getBasicInfo (/www/wwwroot/localhost/api/node_modules/ytdl-core/lib/info.js:74:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Map.getOrSet (/www/wwwroot/localhost/api/node_modules/ytdl-core/lib/cache.js:24:19)
    at async exports.getInfo (/www/wwwroot/localhost/api/node_modules/ytdl-core/lib/info.js:215:14)
    at async Map.getOrSet (/www/wwwroot/localhost/api/node_modules/ytdl-core/lib/cache.js:24:19)
Emitted 'error' event on PassThrough instance at:
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
[nodemon] app crashed - waiting for file changes before starting...
```

from time to time. 
Please help me overcome this error as this cause server crash and I cannot serve the page unless I restart.

**Comment by Asaduji** [comment] 2020-10-23 19:24
Are you on latest?

**Comment by hypo-thesis** [comment] 2020-10-23 19:28
> Are you on latest?

    "ytdl-core": "^3.2.2"

**Comment by Asaduji** [comment] 2020-10-23 19:32
> > Are you on latest?
> 
>     "ytdl-core": "^3.2.2"
> 
> Let me bump myself up to the latest and see. 

This was fixed in 3.4.1, also this is a dupe of #729

**Comment by hypo-thesis** [comment] 2020-10-23 20:04
I get as of the latest version : 

node:events:304
      throw er; // Unhandled 'error' event
      ^

Error: spawn /www/wwwroot/localhost/api/node_modules/ffmpeg-static/ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:269:19)
    at onErrorNT (node:internal/child_process:465:16)
    at processTicksAndRejections (node:internal/process/task_queues:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:275:12)
    at onErrorNT (node:internal/child_process:465:16)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /www/wwwroot/localhost/api/node_modules/ffmpeg-static/ffmpeg',
  path: '/www/wwwroot/localhost/api/node_modules/ffmpeg-static/ffmpeg',
  spawnargs: [
    '-loglevel',
    '0',
    '-hide_banner',
    '-i',
    'pipe:3',
    '-i',
    'pipe:4',
    '-c:v',
    'libx265',
    '-crf',
    '18',
    '-c',
    'copy',
    '-movflags',
    'frag_keyframe+empty_moov',
    '-f',
    'mp4',
    'pipe:5'
  ]
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by hypo-thesis** [comment] 2020-10-23 20:17
Npm didn't do for me I installed Yarn on Ubuntu. It installed the dependencies. Thanks.

**Closed** 2020-10-23 20:17 UTC
