### ISSUE TITLE
Miniget Error issue

### ISSUE THREAD

**Issue by Not-LagsAlot** [fent/node-ytdl-core#880] opened 2021-02-15 04:32 UTC
I am a Discord bot developer and I encountered this issue while played music from the bot using this [package]( https://npmjs.com/distube) , this package required me to download ytdl-core to. What is suprising it works on my other bots but not this even if I copy & paste the code of my other bots

```JS
Status code: 429
    at ClientRequest.<anonymous> (/home/container/node_modules/miniget/dist/index.js:190:31)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:602:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
    at TLSSocket.socketOnData (_http_client.js:475:22)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:298:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at TLSSocket.Readable.push (_stream_readable.js:214:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23) {
  statusCode: 429
}

**Comment by redbrain** [comment] 2021-02-15 04:40
A 429 error means you’re being ratelimited by YouTube. You can use cookies or proxies to get around it, or just wait a few days.

**Comment by fent** [comment] 2021-02-19 10:55
dupe of https://github.com/fent/node-ytdl-core/issues/635

**Closed by fent** 2021-02-19 10:55 UTC
