### ISSUE TITLE
Youtube livestream randomly ends after playing for awhile

### ISSUE THREAD

**Issue by gohjoseph** [fent/node-ytdl-core#255] opened 2018-01-06 14:24 UTC
Hi,

This is where I call `ytdl`,
```
stream = ytdl(
	"https://www.youtube.com/watch?v=" + vid.id, 
	vid.live ? {} : { filter: "audioonly" }
);
```

I think this is due to the stream lagging behind and therefore ending the stream earlier than expected.
Any way or workaround to fix this?

**Comment by fent** [comment] 2018-01-06 16:43
Dupe of #231. I suppose I should adjust the naming of that issue a bit.

**Closed by fent** 2018-01-06 16:43 UTC

**Comment by gohjoseph** [comment] 2018-01-06 17:25
No, it's not a duplicate. The lives stream would play for 10 minutes and the stream ends even though the livestream hasn't stopped. It also stops at random timings. I don't get any request path errors because I'm removing the audioonly filter when the video is a livestream using YouTube API v3
