### ISSUE TITLE
Can't play this video url with 720p60(itag 22) 

### ISSUE THREAD

**Issue by a26364177** [fent/node-ytdl-core#475] opened 2019-08-13 03:54 UTC
https://www.youtube.com/watch?v=FPmybmCAFW8
Can't play this video url with 720p60(itag 22).

**Comment by fent** [comment] 2019-11-25 02:54
yeah this is weird. I'm able to download it, but not play it. and I can play other formats too.

I wonder if the encoder on youtube messed up in the uploading process.

**Comment by fent** [comment] 2020-04-07 01:02
dupe of #163

**Closed by fent** 2020-04-07 01:02 UTC
Labels: bug
