### ISSUE TITLE
No longer works in browserify after "refactor: use `URL` object to parse urls"

### ISSUE THREAD

**Issue by martinbrennan** [fent/node-ytdl-core#882] opened 2021-02-19 08:50 UTC
Until recently I have been able to Browserify ytdl-core so that it works in a browser
(I patch miniget to use a proxy mechanism to make fetches from Youtube or else they would be blocked by CORS)

The refactor: use `URL` object to parse urls change broke things because URL is called Url when require ('url') is invoked in a browser (as opposed to node) environment. Also the browser doesnt have a searchParams property.

I have patched these things and it works again in the browser.

I know this is not an anticipated use case - but I thought you might like to know.

Martin

**Comment by fent** [comment] 2021-02-19 10:52
since browserify is supposed to replicate node behavior, this looks a  browserify issue. but i'm willing to add workarounds to have ytdl-core work in various environments. what does `require('url')` do in browserify? do they not implement it? or is it different?

have you considered using rollup instead? i've h

**Comment by martinbrennan** [comment] 2021-02-19 13:29
Hi
Thanks for the quick answer - I suspect you are right that it is strictly a Browserify issue.
It appears that the constructor URL is called Url in the browser
I am not an Javascript programmer so my fixes are likely suboptimal
Generally I replaced
const { URL } = require('url');
with
const { Url } = require('url);
const URL = Url
To fix that problem.
The second problem was that searchParams is not available in the url library in the browser so I reverted the function setDownloadURL in sig,js to the code used before. It uses url.parse.
Hope thats clear enough.
Thank you for the rollup.js reference. I did not know about it. I will give it a try - though that may not happen until the next Youtube change triggers a rebuild
Martin

**Comment by martinbrennan** [comment] 2021-02-19 16:41
Hello again
Thanks again for the rollup.js suggestion.
I can confirm that rollup builds a bundle that works in the browser - so the problem really is for Browserify to fix - I am happy to use rollup.
Martin

**Comment by fent** [comment] 2021-02-19 22:16
cool! well then, we can keep this issue open to inform those using browserify that it is a browserify issue

**Comment by vegidio** [comment] 2021-02-20 07:39
For the record, since the OP edited his last message and this might not be clear to everyone that comes here, this is **NOT** an issue with Browserify alone.

I also tried to create a bundle to work in the browser using Browserify, Rollup, Webpack and Parcel. All of them failed with the same error `URL is not a constructor`.

**Comment by fent** [comment] 2021-02-20 11:32
@redbrain you had a similar issue on https://github.com/fent/node-ytdl-core/issues/864, did you get a reply on the polyfill repo?

**Comment by redbrain** [comment] 2021-02-20 14:32
The URL polyfill is 5 years old, but someone recently began maintaining it again. I have an issue on their repo so it's definitely on the list of things to fix on their side. Until then, you'll have to use at most `ytdl-core@4.4.4`.
Also this seems like a dupe of #864.

**Comment by martinbrennan** [comment] 2021-02-20 16:00
Hi Vinicius - thanks for letting me know that rollup etc do not work - that saved me a lot of time - Martin

**Comment by redbrain** [comment] 2021-02-22 14:38
Even now, ytdl-core webpacking doesn't seem to work @ version 4.4.4, throwing `Cannot read property 'storyboards' of undefined`.

**Comment by martinbrennan** [comment] 2021-02-22 15:14
Hi redbrain I saw that symptom because searchParams is not a member of url. I had to use an older version of setDownloadURL in sig.js

**Comment by redbrain** [comment] 2021-02-22 20:56
Thanks for the help Martin. Were you able to get it to work? If so, what is the code for setDownloadURL you're currently using?

**Comment by martinbrennan** [comment] 2021-02-23 08:52
Hi Redbrain

Yes I was able to get it all to work with Browserify. I made changes to the require statemements and also reverted the function setDownloadURL. I have pasted both the new require lines and the setDownloadURL that I am using (from sig.js)
Let me know if I have not explained myself very well.
Martin

//const { URL } = require('url');
const { Url } = require('url');
const URL = Url;
const url = require('url');


exports.setDownloadURL = (format, sig) => {
  let decodedUrl;
  if (format.url) {
	decodedUrl = format.url;
  } else {
	return;
  }

  try {
	decodedUrl = decodeURIComponent(decodedUrl);
  } catch (err) {
	return;
  }

  // Make some adjustments to the final url.
  const parsedUrl = url.parse(decodedUrl, true);

  // Deleting the `search` part is necessary otherwise changes to
  // `query` won't reflect when running `url.format()`
  delete parsedUrl.search;

  let query = parsedUrl.query;

  // This is needed for a speedier download.
  // See https://github.com/fent/node-ytdl-core/issues/127
  query.ratebypass = 'yes';
  if (sig) {
	// When YouTube provides a `sp` parameter the signature `sig` must go
	// into the parameter it specifies.
	// See https://github.com/fent/node-ytdl-core/issues/417
	query[format.sp || 'signature'] = sig;
  }

  format.url = url.format(parsedUrl);
};

**Comment by fent** [comment] 2021-03-06 19:48
can the people experiencing this issue test this PR? https://github.com/fent/node-ytdl-core/pull/892

**Comment by MichiruNakam** [comment] 2021-03-07 17:09
> can the people experiencing this issue test this PR? #892

Tested this PR, but I'm getting this error:

Uncaught (in promise) Error: Invalid URL: https://www.youtube.com/get_video_info?video_id=aqz-KE-bpKQ&eurl=https%3A%2F%2Fyoutube.googleapis.com%2Fv%2Faqz-KE-bpKQ&ps=default&gl=US&hl=en
    at doDownload (bundle.js:9504)
    at Item.run (bundle.js:2803)
    at drainQueue (bundle.js:2773)
MinigetError @ bundle.js:9405
doDownload @ bundle.js:9504
Item.run @ bundle.js:2803
drainQueue @ bundle.js:2773
Promise.then (async)
55.ytdl-core @ bundle.js:8799
o @ bundle.js:1
r @ bundle.js:1
(anonymous) @ bundle.js:1
(browserify on Chrome v88.0.4324.146 (Build oficial) (x86_64))

**Comment by mzwtjp** [comment] 2021-03-07 23:08
I just tried with yarn/parcel.
Also needed following changes in node_modules/miniget/dist/index.js so that urls are correctly recognized.

diff index.js.orig index.js
7c7,9
< const url_1 = require("url");
---
> //const url_1 = require("url");
> const { Url } = require("url");
> const url_1 = Url;
99c101,102
<             let urlObj = typeof url === 'string' ? new url_1.URL(url) : url;
---
>             //let urlObj = typeof url === 'string' ? new url_1.URL(url) : url;
>             let urlObj = typeof url === 'string' ? new url_1().parse(url) : url;
103c106,107
<                 path: urlObj.pathname + urlObj.search + urlObj.hash,
---
>                 //path: urlObj.pathname + urlObj.search + urlObj.hash,
>                 path: urlObj.pathname + (urlObj.search || '') + (urlObj.hash || ''),

**Comment by maifeeulasad** [comment] 2021-03-10 07:54
I'm also trying to get this working, here : https://github.com/maifeeulasad/ytdl-mua

**But can't** get it working, the error message I'm getting is : 
```
Uncaught (in promise) TypeError: URL is not a constructor
    at Object.push../node_modules/ytdl-core/lib/url-utils.js.exports.getURLVideoID (url-utils.js:30)
    at Object.push../node_modules/ytdl-core/lib/url-utils.js.exports.getVideoID (url-utils.js:64)
    at Function.push../node_modules/ytdl-core/lib/info.js.exports.<computed> [as getInfo] (info.js:470)
    at ytdl (index.js:19)
    at App.download (App.js:35)
    at App.onDownloadClick (App.js:31)
    at onClick (App.js:43)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
```

**Comment by jamezrin** [comment] 2021-03-10 20:00
Please, try with these 3 PRs. After doing all of these changes the library worked perfectly for me.

- https://github.com/fent/node-m3u8stream/pull/88
- https://github.com/fent/node-miniget/pull/58
- https://github.com/fent/node-ytdl-core/pull/892

**Comment by TimeForANinja** [comment] 2021-05-04 16:29
can you guys do me a favor
the `require('URL')` was made obsolete in v10 (which is our minimum version)
URL should also be available in all browsers [MDN](https://developer.mozilla.org/en-US/docs/Web/API/URL#browser_compatibility)
can you check if just removing the 4 requires all together solves this problem?
the ci has no problems with these changes <https://github.com/TimeForANinja/node-ytdl-core/commit/eb08a979d83b0d5989a85a5ecbc1724a7d2d5282>

**Comment by redbrain** [comment] 2021-05-07 22:36
Seems to work for me.
That being said I'm using newest Node and Chromium at the moment.
If someone could check with stable node and browsers that would be much appreciated.
Looking forward to using this library with rollup again!

**Comment by elgiano** [comment] 2021-05-20 10:30
Tried with Browserify 17.0, Node 16 and Firefox 88.0.
Just removing URL import statements (also from miniget and m3u8stream, so 6 in total) seems to fix the `URL is not a constructor` issue.

However, everything I do with ytdl from a browser ends up in CORS issues... am I missing something, or the in-browser use case is kind of impossible with common browsers?

**Comment by martinbrennan** [comment] 2021-05-20 11:03
Hi elgiano

I use this in an embedded application - a Raspberry Pi with a webserver.  The Pi serves the page containing the ytdl bundle.  I modify miniget slightly so the browser uses the Pi to do web fetches (by proxy) that would otherwise be blocked by CORS restrictions. 

You can force the Chrome browser to ignore CORS restrictions - its not something you would do every day because of the warnings at startup - but useful for testing. Basically you invoke chrome with --disable-web-security on the command line.

Martin

**Comment by elgiano** [comment] 2021-05-20 11:34
Thanks! 
I ended up using an extension on Firefox called cors-everywhere. Now I can go on youtube and preload the whole video by pasting some ytdl-powered code right in the console :)

**Comment by redbrain** [comment] 2021-05-20 23:56
You can also use a CORS proxy (such as AllOrigins) to bypass CORS restrictions without the need for an extension.

**Closed** 2021-05-27 17:40 UTC
Labels: needs more info

**Comment by thefloppydriver** [comment] 2021-11-17 01:03
This issue has come back up with browserify on version 4.9.1.
I get the following errors
`bundle.js:14298 Error checking for updates: Invalid URL: https://api.github.com/repos/fent/node-ytdl-core/releases/latest
bundle.js:10086 Uncaught (in promise) Error: Invalid URL: https://www.youtube.com/get_video_info?video_id=ormQQG2UhtQ&c=TVHTML5&cver=7.20210622.10.00&eurl=https%3A%2F%2Fyoutube.googleapis.com%2Fv%2FormQQG2UhtQ&ps=default&gl=US&hl=en&html5=1`

this is awful lmao
