### ISSUE TITLE
Error in ytdl-core while requesting video info

### ISSUE THREAD

**Issue by mh4ck** [fent/node-ytdl-core#354] opened 2018-08-17 09:51 UTC
My Service run sometimes in this error and exit itself. I don't on which videos exactly  and i don't know how to work around it. Maybe smbd. could help.

`data:    index.js:28736 - /var/www/youtube-repeat/node_modules/ytdl-core/lib/util.js:395
data:    index.js:28736 -     id: channelMatch[1],
data:    index.js:28736 -                     ^
data:    index.js:28736 - TypeError: Cannot read property '1' of null
data:    index.js:28736 -     at Object.exports.getAuthor (/var/www/youtube-repeat/node_modules/ytdl-core/lib/util.js:395:21)
data:    index.js:28736 -     at request (/var/www/youtube-repeat/node_modules/ytdl-core/lib/info.js:72:20)
data:    index.js:28736 -     at IncomingMessage.res.on (/var/www/youtube-repeat/node_modules/miniget/lib/index.js:75:11)
data:    index.js:28736 -     at emitNone (events.js:91:20)
data:    index.js:28736 -     at IncomingMessage.emit (events.js:185:7)
data:    index.js:28736 -     at endReadableNT (_stream_readable.js:974:12)
data:    index.js:28736 -     at _combinedTickCallback (internal/process/next_tick.js:80:11)
data:    index.js:28736 -     at process._tickCallback (internal/process/next_tick.js:104:9)`

**Comment by fent** [comment] 2018-08-17 14:37
Dupe of #349 

Are you sure you have the latest version of ytdl-core? This error has been patched

**Closed by fent** 2018-08-17 14:37 UTC
Labels: duplicate
