### ISSUE TITLE
TypeError: URL is not a constructor

### ISSUE THREAD

**Issue by abdullah-19** [fent/node-ytdl-core#890] opened 2021-02-27 09:57 UTC
I'm trying to integrate ytdl-core in my application like this : 
```
const ytdl = require('ytdl-core');
url = 'https://www.youtube.com/watch?v=jrNLsC_Y9Oo'
ytdl(url);
```

Full error message : 
```
url-utils.js:30 Uncaught (in promise) TypeError: URL is not a constructor
    at Object.push../node_modules/ytdl-core/lib/url-utils.js.exports.getURLVideoID (url-utils.js:30)
    at Object.push../node_modules/ytdl-core/lib/url-utils.js.exports.getVideoID (url-utils.js:64)
    at Function.push../node_modules/ytdl-core/lib/info.js.exports.<computed> [as getInfo] (info.js:470)
    at ytdl (index.js:19)
    at App.download (App.js:30)
    at App.onDownloadClick (App.js:26)
    at onClick (App.js:38)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4070)
    at executeDispatch (react-dom.development.js:8243)
    at processDispatchQueueItemsInOrder (react-dom.development.js:8275)
    at processDispatchQueue (react-dom.development.js:8288)
    at dispatchEventsForPlugins (react-dom.development.js:8299)
    at react-dom.development.js:8508
    at batchedEventUpdates$1 (react-dom.development.js:22396)
    at batchedEventUpdates (react-dom.development.js:3745)
    at dispatchEventForPluginEventSystem (react-dom.development.js:8507)
    at attemptToDispatchEvent (react-dom.development.js:6005)
    at dispatchEvent (react-dom.development.js:5924)
    at unstable_runWithPriority (scheduler.development.js:646)
    at runWithPriority$1 (react-dom.development.js:11276)
    at discreteUpdates$1 (react-dom.development.js:22413)
    at discreteUpdates (react-dom.development.js:3756)
    at dispatchDiscreteEvent (react-dom.development.js:5889)
```

**Comment by redbrain** [comment] 2021-02-27 15:44
Check that you're on a version of Node that supports URL construction. I recommend using the v14 LTS.
Also, make sure you're on the latest version of ytdl-core library.

**Comment by CarmenLexa** [comment] 2021-03-01 18:09
I have the same problem and installed the latest version of node.js 14.16.0 and the latest version of ytdl-core, however it follows the same error @redbrain

**Comment by maifeeulasad** [comment] 2021-03-02 08:33
I also faced this same error, I had faced this issue a year back. Now I'm trying to resume on that project, I'm facing it again.

**Comment by zhukaijun0629** [comment] 2021-03-03 01:40
I have the same problem using react.

**Comment by fent** [comment] 2021-03-06 19:47
dupe of https://github.com/fent/node-ytdl-core/issues/882

**Closed by fent** 2021-03-06 19:47 UTC
