### ISSUE TITLE
Error caused when end stream early

### ISSUE THREAD

**Issue by SquirrelsMcGee** [fent/node-ytdl-core#73] opened 2016-05-08 03:51 UTC
I am attempting to write a bot for a Discord server that I am an admin for, this bot needs to have youtube playback in the voice channels.

The following error is caused when trying to end a stream early, i.e. when someone calls the function to play a video while a video is already being played.

`Error: write after end
    at writeAfterEnd (_stream_writable.js:166:12)
    at PassThrough.Writable.write (_stream_writable.js:217:5)
    at IncomingMessage.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at IncomingMessage.emit (events.js:188:7)
    at IncomingMessage.Readable.read (_stream_readable.js:387:10)
    at flow (_stream_readable.js:764:26)
    at resume_ (_stream_readable.js:744:3)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

I've searched around and read some of the docs and discovered that none of the methods for ending a stream early work, at least for me.
i've tested: 
`stream.destroy` (stream#destroy did not work at all, crashing the bot entirely)
`stream.end`
`stream.abort`

these seem to produce errors saying that they cannot read *blank* of undefined

pls forgive any spelling mistakes as it is like, 5 in the morning right now and im fed up trying to get this to work frankly

**Comment by fent** [comment] 2016-05-08 06:48
This looks similar to #65

`stream.destroy()` should be used, what error do you get when the bot crashes?

**Comment by SquirrelsMcGee** [comment] 2016-05-08 10:42
Here is the code im using to play videos,
https://paste.cuntflaps.me/opomaxinik.js

When the command to run this is entered, this error is produced in the console
`TypeError: Cannot read property 'destroy' of undefined
    at Client.onMessage (C:\Users\Win 8 - Steer\discord\bots\test.js:123:13)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at WebSocket.websocket.onmessage (C:\Users\Win 8 - Steer\discord\bots\node_modules\discord.js\lib\Client\InternalClient.js:90:15)
    at WebSocket.onMessage (C:\Users\Win 8 - Steer\node_modules\ws\lib\WebSocket.js:442:14)
    at emitTwo (events.js:111:20)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (C:\Users\Win 8 - Steer\node_modules\ws\lib\WebSocket.js:841:10)
    at C:\Users\Win 8 - Steer\node_modules\ws\lib\Receiver.js:536:18
    at Receiver.applyExtensions (C:\Users\Win 8 - Steer\node_modules\ws\lib\Receiver.js:371:5)`

**Comment by fent** [comment] 2016-05-08 14:04
The `stream` that you're referring to there is null because you declared `var stream = ...` in a later line in the same scope.

Keep a reference to the playing stream by assigning it to `mybot.voiceConnection.stream` for example.

BTW, you don't need to check for the video id, ytdl will throw an error when called if it can't find one.

**Comment by SquirrelsMcGee** [comment] 2016-05-08 14:19
I see, I suppose I could also try defining the stream as global?
Although i'm unsure how to do that

**Comment by fent** [comment] 2016-05-08 22:09
Global to the bot yeah.

Let me know it ends up working.

**Comment by SquirrelsMcGee** [comment] 2016-05-08 22:39
I'll have to let you know tomorrow unfortunately, dont want to stay up late again

**Comment by SquirrelsMcGee** [comment] 2016-05-09 17:26
Ok i've made the stream variable global, setting its default value to null; `var stream = null;`
Here is the update version, https://paste.cuntflaps.me/ifopufamoj.js
Unfortunately i'm still getting the "write after end at writeAfterEnd" error as before

**Comment by fent** [comment] 2016-05-09 23:38
Just to make sure, are you using the latest version of ytdl?

**Comment by SquirrelsMcGee** [comment] 2016-05-10 17:54
I just reinstalled it using `npm install ytdl-core` and there has been no change

**Comment by Razzile** [comment] 2016-05-10 17:57
I also get this error.

**Comment by fent** [comment] 2016-05-14 10:31
Just pushed a potential fix. I couldn't reproduce this myself, but please update and test if this works for you.

**Comment by SquirrelsMcGee** [comment] 2016-05-14 10:40
This is perfect!
I'm no longer getting the error, Thanks for the help!

**Closed** 2016-05-14 10:43 UTC
