### ISSUE TITLE
How can I make it less laggy ytdl-core

### ISSUE THREAD

**Issue by FrostyHyperX** [fent/node-ytdl-core#405] opened 2019-01-20 14:51 UTC
```
        let dispatcher = queue.connection.playStream(ytdl(music.url,{quality: 'highestaudio'}))
            .on('end', () => {
                queue.musics.shift();
                votes.votes = 0;
                votes.voters = [];
                setTimeout(() => {
                    bot.play(guild, queue.musics[0]);
                }, 250);
            })
             .on('progress', (d, total, length) => {
            console.log('progress', total / length);
            })
             .on('error', err => console.error(err));
           
  
```
How can i download the video and play it

**Comment by fent** [comment] 2019-01-20 20:56
So it does play, but slowly?

**Comment by FrostyHyperX** [comment] 2019-01-21 09:06
Not slowly but laggy

**Comment by TimeForANinja** [comment] 2019-01-21 09:32
You might try caching more of the ytdl stream

**Comment by FrostyHyperX** [comment] 2019-01-21 09:46
How

**Comment by FrostyHyperX** [comment] 2019-01-21 10:34
will it be less laggy if i download it first and after play it ?

**Comment by TimeForANinja** [comment] 2019-01-21 12:19
It could - should be worth a shot

Either you first download it to a file or you use sth like https://www.npmjs.com/package/stream-buffers

**Comment by FrostyHyperX** [comment] 2019-01-21 13:16
`bot.play = (guild, music) => {
        let queue = bot.queue.get(guild.id);
        let votes = bot.votes.get(guild.id)
        if (!music) {
            queue.voiceChannel.leave();
            bot.queue.delete(guild.id);
            bot.votes.delete(guild.id);
            return queue.textChannel.send(`🎵 finish`);
        }
        let music1 = ytdl(music.url);


        music1.pipe(fs.createWriteStream('video.mp3'))
           let dispatcher= queue.connection.playStream(fs.createReadStream('video.mp3'))
            .on('end', () => {
                queue.musics.shift();
                votes.votes = 0;
                votes.voters = [];
                setTimeout(() => {
                    bot.play(guild, queue.musics[0]);
                }, 250);
            })
             .on('progress', (d, total, length) => {
            console.log('progress', total / length);
            })
             .on('error', err => console.error(err));
           
  
        dispatcher.setVolumeLogarithmic(queue.volume / 100);
        
        queue.textChannel.send(`🎵 **${music.title}** now playing`);
           
          `

**Comment by fent** [comment] 2019-01-21 14:53
The solution too this might be the same as https://github.com/fent/node-ytdl-core/issues/402, to use `highWaterMark`. Look in the comments for that issue for more, but basically, you'd use a higher value for `highWaterMark`, default is 16kb which may not be enough.

    ytdl(url, { highWaterMark: 1<<25 })

I may just increase the default value for this. My concern is people won't like that ytdl takes more memory to use. But surely making it only a couple of mb people won't mind?

**Comment by FrostyHyperX** [comment] 2019-01-21 15:32
I'm a newbie can you help me a little bit with code

**Comment by sasjafor** [comment] 2019-01-21 16:34
I have done some testing, and it seems that the "lagginess" is caused by some form of rate limiting from youtube's side. At least that is what I'm suspecting. With a low value for `highWaterMark` (I tried simply 1), "skipping", that is not playing videos to the end and then starting to play a different or the same video, but with a new stream, everything works fine (except for #402).
However, with a higher value for `highWaterMark`, "skipping" causes the stream to be slow (I assume download is slower than playback), which causes lag. For me, the higher the value of `highWaterMark`, the worse it gets. With values of around 500KB, it manages to catch up after a few seconds, but with higher values it didn't seem to catch up.

So this seems to be a bit of trade-off situation. Use higher values for `highWaterMark` and avoid #402, but have potentially laggier playback. Use lower values and have smoother playback but be plagued by #402.

**Comment by FrostyHyperX** [comment] 2019-01-21 16:38
My bot its not even smooth

**Comment by FrostyHyperX** [comment] 2019-01-21 16:44
`        
let dispatcher = queue.connection.playStream(ytdl(music.url,{filter: 'audioonly'},{quality: 'highestaudio'},{ highWaterMark: 1<<25 } ))
            .on('end', () => {
                queue.musics.shift();
                votes.votes = 0;
                votes.voters = [];
                setTimeout(() => {
                    bot.play(guild, queue.musics[0]);
                }, 250);
            })
            .on('error', err => console.error(err));
        dispatcher.setVolumeLogarithmic(queue.volume / 100);

        queue.textChannel.send(`🎵 **${music.title}** сейчас играет`);`
it didn`t help

**Comment by sasjafor** [comment] 2019-01-21 17:55
> `
> let dispatcher = queue.connection.playStream(ytdl(music.url,{filter: 'audioonly'},{quality: 'highestaudio'},{ highWaterMark: 1<<25 } ))
> .on('end', () => {
> queue.musics.shift();
> votes.votes = 0;
> votes.voters = [];
> setTimeout(() => {
> bot.play(guild, queue.musics[0]);
> }, 250);
> })
> .on('error', err => console.error(err));
> dispatcher.setVolumeLogarithmic(queue.volume / 100);
> 
> ```
>     queue.textChannel.send(`🎵 **${music.title}** сейчас играет`);`
> ```
> it didn`t help

Try using `highWaterMark: 5`, you might experience #402, but the laggy playback might go away.

**Comment by FrostyHyperX** [comment] 2019-01-22 12:20
Nothing changed

**Comment by sasjafor** [comment] 2019-01-22 14:04
If you are using discord.js, you can try setting their `highWaterMark` to a lower value (which works well for me). I'm using 1. When I had accidentally increased that value instead of the one in ytdl-core, I had also experienced laggy/choppy playback.

Like so:
`let dispatcher = queue.connection.playStream(ytdl(music.url,{filter: 'audioonly', quality: 'highestaudio', highWaterMark: 1<<25 }), {highWaterMark: 1})`

If that doesn't help you can try switching to the master branch of discord.js. I'm using that version.

**Comment by FrostyHyperX** [comment] 2019-01-22 15:00
That worked

**Comment by FireController1847** [comment] 2019-02-02 01:45
Closing due to issue being solved.

**Closed by FireController1847** 2019-02-02 01:45 UTC
Labels: support
