### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hansputera** [fent/node-ytdl-core#592] opened 2020-03-19 01:37 UTC
Could not extract html5player key: https://www.youtube.com/s/player/9b926fb0/player_ias.vflset/en_US/base.js

How to fix it?

**Comment by mahhov** [comment] 2020-03-21 16:37
I've also encountered this error and just ignored it. It seems to be not-constant, i.e. it will go away if you retry.

**Comment by mh4ck** [comment] 2020-03-21 18:54
Duplicate of this: https://github.com/fent/node-ytdl-core/issues/591

**Comment by fent** [comment] 2020-03-22 00:05
closed by new version

**Closed by fent** 2020-03-22 00:05 UTC
