### ISSUE TITLE
Invalid regular expression: missing /

### ISSUE THREAD

**Issue by GreepTheSheep** [fent/node-ytdl-core#1110] opened 2022-08-18 00:09 UTC
Since 1 or 2 hours, all videos passed on ytdl-core return this "Invalid regular expression" error

Stack trace:
```
evalmachine.<anonymous>:11
"mfZru","cfYAzm",1897615910,414154674,"IluoVc5",null,1,"XsmT",-659785013,577478260,-419211961,1087899650,/,,[/,913,/](,)};Wka(ncode);
                                                                                                         ^

SyntaxError: Invalid regular expression: missing /
    at new Script (node:vm:100:7)
    at exports.decipherFormats (D:\Documents\GitHub\ReAllToMP3\node_modules\ytdl-core\lib\sig.js:116:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async exports.getInfo (D:\Documents\GitHub\ReAllToMP3\node_modules\ytdl-core\lib\info.js:401:17)
```

ytdl-core version: 4.11.0

Edit: Temporary fix linked here: https://github.com/fent/node-ytdl-core/issues/1110#issuecomment-1219856316

**Comment by Mikecerc** [comment] 2022-08-18 00:11
I'm having the same problem as well. Receiving the same error as above. Everything worked fine yesterday.

**Comment by cchen028** [comment] 2022-08-18 00:16
Experiencing same issue, getting identical stack trace as well.

**Comment by MohamedMontasser03** [comment] 2022-08-18 00:46
Okay I am trying to figure out the problem but this is my first time working with the source code of this project and with the youtube cipher algorithm so it's taking a while anyways I've narrowed the problem down to a problem with evaluating nTransformScript because the code returned from youtube is for some reason broken, that's the conclusion I reached

**Comment by TaylorDuck72** [comment] 2022-08-18 00:57
Still having same problem

**Comment by austinharms** [comment] 2022-08-18 01:09
this solved it for me
https://github.com/fent/node-ytdl-core/issues/1108#issuecomment-1212500413

**Comment by Hakunek** [comment] 2022-08-18 01:13
If you need to use it rn and don't want to/can't tinker inside module
downgrade to version 4.10.0
npm command:
`npm i ytld-core@4.10.0`
only versions 4.11.x seems affected as of now

**Comment by austinharms** [comment] 2022-08-18 01:15
I had the issue on version 4.10.0, and 4.9.? (I can't remember the last digit)

**Comment by MohamedMontasser03** [comment] 2022-08-18 01:18
> this solved it for me [#1108 (comment)](https://github.com/fent/node-ytdl-core/issues/1108#issuecomment-1212500413)

Not sure if that's the proper solution or not but it does work

**Comment by MidSpike** [comment] 2022-08-18 01:49
Can reproduce: with almost all videos that I test with:
```
Trace: evalmachine.<anonymous>:11
"mfZru","cfYAzm",1897615910,414154674,"IluoVc5",null,1,"XsmT",-659785013,577478260,-419211961,1087899650,/,,[/,913,/](,)};Wka(ncode);
                                                                                                         ^

SyntaxError: Invalid regular expression: missing /
```

**Comment by PowerBuxoK** [comment] 2022-08-18 02:56
same problem with any video:
`evalmachine.<anonymous>:11
"mfZru","cfYAzm",1897615910,414154674,"IluoVc5",null,1,"XsmT",-659785013,577478260,-419211961,1087899650,/,,[/,913,/](,)};Wka(ncode);
                                                                                                         ^

SyntaxError: Invalid regular expression: missing /
    at new Script (node:vm:100:7)
    at Object.exports.decipherFormats (C:\db\db\node_modules\ytdl-core\lib\sig.js:116:51)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async exports.getInfo (C:\db\db\node_modules\ytdl-core\lib\info.js:401:17)

Node.js v17.5.0`

**Comment by PowerBuxoK** [comment] 2022-08-18 03:00
same problem with any video:

evalmachine.:11
"mfZru","cfYAzm",1897615910,414154674,"IluoVc5",null,1,"XsmT",-659785013,577478260,-419211961,1087899650,/,,[/,913,/](https://github.com/fent/node-ytdl-core/issues/,)};Wka(ncode);
^

SyntaxError: Invalid regular expression: missing /
at new Script (node:vm:100:7)
at Object.exports.decipherFormats (C:\db\db\node_modules\ytdl-core\lib\sig.js:116:51)
at runMicrotasks ()
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async Promise.all (index 0)
at async exports.getInfo (C:\db\db\node_modules\ytdl-core\lib\info.js:401:17)

Node.js v17.5.0

**Comment by PowerBuxoK** [comment] 2022-08-18 03:04
same problem with any video
```evalmachine.<anonymous>:11
"mfZru","cfYAzm",1897615910,414154674,"IluoVc5",null,1,"XsmT",-659785013,577478260,-419211961,1087899650,/,,[/,913,/](,)};Wka(ncode);
                                                                                                         ^

SyntaxError: Invalid regular expression: missing /
    at new Script (node:vm:100:7)
    at Object.exports.decipherFormats (C:\DiscordBots\Botik_v2.0\node_modules\ytdl-core\lib\sig.js:116:51)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async exports.getInfo (C:\DiscordBots\Botik_v2.0\node_modules\ytdl-core\lib\info.js:401:17)

Node.js v17.5.0```

**Comment by dskaiser82** [comment] 2022-08-18 05:36
@austinharms
I went into package.json changed the version to
 "ytdl-core": "4.10.0"
 
 deleted my node modules 
 and ran yarn (yarn for me)
 
 I'm back!
 
 Holy shit I was about to wipe my system because this week I had some pc malware issues I solved.  But when in doubt CHECK the GITHUB! I was that close....thanks to everyone for the comments...
 
 I skew front-end but hoping devs solve the issue?

**Comment by dskaiser82** [comment] 2022-08-18 05:39
But if we know 4.10.0 we know that the PR that came after introduced a bug....so whats the PR for 4.10.1?

**Comment by dskaiser82** [comment] 2022-08-18 05:49
@dsnsgithub  on 4.10.0 its slow but downloading but will test audio when its up

**Comment by dsnsgithub** [comment] 2022-08-18 05:52
@dskaiser82 Thank you, your fix works. ytdl-core@4.10.0 seems to be working while ytdl-core@4.11.0 seems to have a problem with dependences.

**Comment by dskaiser82** [comment] 2022-08-18 06:05
@dsnsgithub Good!  Yean I have audio working fine too on the video below....but did take a longer than normal....I want to test another vid to see if speeds can be faster....but for now I'll take this band aid fix

https://www.youtube.com/watch?v=moiS5zDIuPM

**Comment by dskaiser82** [comment] 2022-08-18 06:09
Yeah I think this version is slower than before, but I do like to do highest Audio, Highest Video

**Comment by gatecrasher777** [comment] 2022-08-18 06:43
Last week it was closing braces in strings. To confuse parsers.
This week YouTube have thrown some regex into their code spaghetti.

**Comment by WaqasIbrahim** [comment] 2022-08-18 11:12
Can anyone please attach base.js file that has this issue because I can't reproduce this on my end.

**Comment by gatecrasher777** [comment] 2022-08-18 11:48
@WaqasIbrahim sent via email

**Comment by danielsss** [comment] 2022-08-18 11:51
I've got the same issue +1

**Comment by gatecrasher777** [comment] 2022-08-18 12:10
Needs  exports.cutAfterJSON in util.js to skip over regex.  

When it encounters
```javascript

/,,[/,913,/](,)}/

```
as an array value in base.js it sees the } as the end of the n code function that is being parsed. So evaluation breaks.

**Comment by WaqasIbrahim** [comment] 2022-08-18 12:41
I just tested ncode extraction on a file @gatecrasher777 sent. The solution I suggested in the closed issue: https://github.com/fent/node-ytdl-core/issues/1108#issuecomment-1212500413 still works.

**Comment by aymenitc** [comment] 2022-08-18 13:01
> I just tested ncode extraction on a file @gatecrasher777 sent. The solution I suggested in the closed issue: [#1108 (comment)](https://github.com/fent/node-ytdl-core/issues/1108#issuecomment-1212500413) still works.

this fix is working for me 100%

**Comment by arinmodi** [comment] 2022-08-18 14:57
downgrading the version decreases the singnificat download spped, how can i solve that ?

**Comment by CuteSkyler** [comment] 2022-08-18 17:32
For some reason, I kept getting `HTTPError [FetchError]: request to https://discord.com/api/v7/channels/[channelid]/messages failed, reason: read ECONNRESET` in the new update, if it is of any help. Downgrading to ytdl-core@4.10.0 fixed it for me.

**Comment by dskaiser82** [comment] 2022-08-18 19:13
@arinmodi Thats the state I chose, degraded version but MUCH slower download speeds.....no PR's in yet for the fix right?

**Comment by GreepTheSheep** [comment] 2022-08-18 19:16
Made a fork of the temporary fix here: https://github.com/GreepTheSheep/node-ytdl-core

You can add it on your package.json with npm `npm i ytdl-core@https://github.com/GreepTheSheep/node-ytdl-core`

**Comment by dskaiser82** [comment] 2022-08-18 19:23
@[GreepTheSheep](https://github.com/GreepTheSheep)
Good stuff!
I took the fix one step further and did a Pull Request so we can get this fix in.

https://github.com/fent/node-ytdl-core/pull/1111

**Comment by LeGeek01** [comment] 2022-08-18 21:21
same problem with any videos, I have the latest version of ytdl-core

**Comment by gatecrasher777** [comment] 2022-08-18 21:25
> PR waiting for approval....anyone know who has PR approval/merge rights? PR: #1111

@TimeForANinja

**Comment by LeGeek01** [comment] 2022-08-18 21:28
downgrading to 4.10.0 solved the problem for me! Waiting for a new version...

**Comment by nukeop** [comment] 2022-08-18 22:30
Let me know if I can throw a few bucks the maintainers' way, they're doing God's work.

**Comment by ShadowLp174** [comment] 2022-08-19 14:34
This error message just sudenly changed... yesterday it was the invalid regex, now it's something new:

```Bash
evalmachine.<anonymous>:24
c[72],c[6]),(0,c[85])(c[11]),(0,c[41])(c[39],c[28],(0,c[66])()),(0,c[78])(c[Math.pow(6,2)+122+-119],c[new Date("Wednesday December 31 1969 19:00:1
4 CDT")/1E3])}catch(d){(0<c[0]||(((0,c[80])(c[60],c[88]),c[80])(c[21],c[88]),0))&&(0,c[17])((0,c[70])(c[6]),c[78],c[88],c[12])}try{2<c[91]&&(1<c[5
3]?(0,c[17])((0,c[80])(c[82],c[6]),c[78],c[39],c[5]):((0,c[45])(c[49],c[88]),c[78])(c[88],c[86])),(0,c[17])((0,c[85])(c[31]),c[41],c[88],c[75],(0,
c[35])())}catch(d){}};Wka(ncode);




                    ^

SyntaxError: Missing catch or finally after try
    at new Script (node:vm:100:7)
    at Object.exports.decipherFormats (D:\JS\revolt butler\node_modules\ytdl-core\lib\sig.js:116:51)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async exports.getInfo (D:\JS\revolt butler\node_modules\ytdl-core\lib\info.js:401:17)
```

**Comment by dskaiser82** [comment] 2022-08-20 02:26
PR: https://github.com/fent/node-ytdl-core/pull/1111


We have some approvals but this is the blocker:
"First-time contributors need a maintainer to approve running workflows. [Learn more.](https://docs.github.com/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks)
1 successful check"

Who is a maintainer?

**Comment by ShadowLp174** [comment] 2022-08-20 08:46
> This error message just sudenly changed... yesterday it was the invalid regex, now it's something new:
> 
> ```shell
> evalmachine.<anonymous>:24
> c[72],c[6]),(0,c[85])(c[11]),(0,c[41])(c[39],c[28],(0,c[66])()),(0,c[78])(c[Math.pow(6,2)+122+-119],c[new Date("Wednesday December 31 1969 19:00:1
> 4 CDT")/1E3])}catch(d){(0<c[0]||(((0,c[80])(c[60],c[88]),c[80])(c[21],c[88]),0))&&(0,c[17])((0,c[70])(c[6]),c[78],c[88],c[12])}try{2<c[91]&&(1<c[5
> 3]?(0,c[17])((0,c[80])(c[82],c[6]),c[78],c[39],c[5]):((0,c[45])(c[49],c[88]),c[78])(c[88],c[86])),(0,c[17])((0,c[85])(c[31]),c[41],c[88],c[75],(0,
> c[35])())}catch(d){}};Wka(ncode);
> 
> 
> 
> 
>                     ^
> 
> SyntaxError: Missing catch or finally after try
>     at new Script (node:vm:100:7)
>     at Object.exports.decipherFormats (D:\JS\revolt butler\node_modules\ytdl-core\lib\sig.js:116:51)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async Promise.all (index 0)
>     at async exports.getInfo (D:\JS\revolt butler\node_modules\ytdl-core\lib\info.js:401:17)
> ```

Wanted to add that this can too be fixed by downgrading to 4.10.0

**Comment by gatecrasher777** [comment] 2022-08-20 10:28
Downgrading to 4.10.0 will mean the N transform gracefully fails.  Everything will work, but downloads will be throttled.

**Closed** 2022-08-26 11:22 UTC

**Comment by nukeop** [comment] 2022-09-01 10:07
They're at it again, it stopped working just today.

**Comment by aymenitc** [comment] 2022-09-01 11:06
Today I'm get the same error again 
: 
`Invalid regular expression: missing /`

**Comment by MidSpike** [comment] 2022-09-01 17:23
```
Trace: evalmachine.<anonymous>:13
-1929233002,b,/,][};Xka(ncode);
              ^

SyntaxError: Invalid regular expression: missing /
    at new Script (node:vm:100:7)
    at Object.exports.decipherFormats (C:\hi-there-github\node_modules\ytdl-core\lib\sig.js:116:51)
```

**Comment by ThatGuyJacobee** [comment] 2022-09-01 17:25
Same here receiving since about yesterday 10pm UK time: 
> Invalid regular expression: missing /

**Comment by aymenitc** [comment] 2022-09-01 17:28
Found a fix: #1111

Same solution as the previous regex errors.

**Comment by LeGeek01** [comment] 2022-09-01 18:56
yes the error come's back

**Comment by LeGeek01** [comment] 2022-09-01 19:01
and downgrading to 4.10.0 solved the problem, again

**Comment by nukeop** [comment] 2022-09-01 19:07
Is it throttled though?

**Comment by milanbabiclibrafire** [comment] 2023-05-24 11:30
This worked for me:
1. delete node_module, package-lock.json
2. "ytdl-core": "github:milanbabiclibrafire/node-ytdl-core"
3. npm i
