### ISSUE TITLE
Status code 429

### ISSUE THREAD

**Issue by encloinc** [fent/node-ytdl-core#445] opened 2019-07-10 00:34 UTC
```
at ClientRequest.httpLib.get (/home/nowuser/src/node_modules/miniget/lib/index.js:123:19)
Jul 09 2019 19:08:54:125    at Object.onceWrapper (events.js:315:30)
Jul 09 2019 19:08:54:126    at emitOne (events.js:116:13)
Jul 09 2019 19:08:54:126    at ClientRequest.emit (events.js:211:7)
Jul 09 2019 19:08:54:126    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:543:21)
Jul 09 2019 19:08:54:126    at HTTPParser.parserOnHeadersComplete (_http_common.js:112:17)
Jul 09 2019 19:08:54:126    at TLSSocket.socketOnData (_http_client.js:440:20)
Jul 09 2019 19:08:54:127    at emitOne (events.js:116:13)
Jul 09 2019 19:08:54:127    at TLSSocket.emit (events.js:211:7)
Jul 09 2019 19:08:54:127    at addChunk (_stream_readable.js:263:12)
```
I seem to be getting this error as of today, its weird because ive never gotten this error before. I dont know what is causing it exactly, but I know its coming from this library. Im using ytdl v.0.29.2

**Comment by fent** [comment] 2019-07-10 01:01
Dupe of https://github.com/fent/node-ytdl-core/issues/444, let's keep discussion in one issue

**Closed by fent** 2019-07-10 01:01 UTC
